language: node_js
node_js:
  - '7.6'
services:
  - mongodb
cache:
  directories:
    - node_modules
git:
  depth: 3
install:
  - git clone $GIT_CLONE_REMOTE
  - cd $REPO_NAME
  - git checkout $TRAVIS_BRANCH
  - npm i
script: npm run travis-script
after_script:
  - npm report-coverage
before_script:
  - npm install -g gulp-cli
before_deploy:
  - if [ "$TRAVIS_BRANCH" == "develop" ] ; then if [ "$TRAVIS_PULL_REQUEST" == "false"] ; then bash travis.sh ; fi ; fi
deploy:
  app: $PROVIDER_APP_NAME
  provider: $PROVIDER
  on:
    repo: $PROVIDER_REPO_NAME
    all_branches: true
  api_key:
    secure: $TRAVIS_SECURE_API_KEY
